server:
  port: 9091
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.boot: INFO
    com.spring.web-flux: ERROR
    org.springframework.web.reactive: ERROR
    org.springframework.r2dbc: DEBUG

debug: true